import React from 'react'
import type { AppProps } from 'next/app'
import { ToastContainer } from 'react-toastify'
import { ImageProvider } from 'contexts/Image'
import { ChakraProvider } from '@chakra-ui/react'
import theme from 'styles'
import Head from 'next/head'

import 'react-toastify/dist/ReactToastify.css'

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>TI-VI</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favorite.png" />
			</Head>

			<ChakraProvider theme={theme}>
				<ToastContainer
					theme="dark"
					position="bottom-right"
					autoClose={3000}
					newestOnTop={false}
					rtl={false}
					pauseOnHover
					pauseOnFocusLoss
				/>
				<ImageProvider>
					<Component {...pageProps} />
				</ImageProvider>
			</ChakraProvider>
		</>
	)
}

export default MyApp
