import React from 'react'
import type { AppProps } from 'next/app'
import { ImageProvider } from 'contexts/Image'
import { ChakraProvider } from '@chakra-ui/react'
import theme from 'styles'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>TI-VI</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favorite.png" />
			</Head>
			<ChakraProvider theme={theme}>
				<ImageProvider>
					<Component {...pageProps} />
				</ImageProvider>
			</ChakraProvider>
		</>
	)
}

export default MyApp
