import React from 'react'
import Head from 'next/head'

import Classificator from 'Containers/Classificator'

const Page = () => (
	<>
		<Head>
			<title>Classificador</title>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<Classificator />
	</>
)

export default Page
