import React from 'react'
import Head from 'next/head'
import Home from '../Containers/Home'
import { ChakraProvider, theme } from '@chakra-ui/react'
import { ImageProvider } from 'contexts/Image'

const Page = () => (
	<ChakraProvider theme={theme}>
		<ImageProvider>
			<>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Home />
			</>
		</ImageProvider>
	</ChakraProvider>
)

export default Page
